const sidebars = {
  bedocSidebar: [{type: 'autogenerated', dirName: 'bedoc'}],
  muddlerSidebar: [{type: 'autogenerated', dirName: 'muddler'}],
  mpackageSidebar: [{type: 'autogenerated', dirName: 'mudlet-mpackage'}],
  chromeManifest: [{type: 'autogenerated', dirName: 'chrome-manifest'}],
};

export default sidebars;
